### ISSUE TITLE
Kill Nette dependency

### ISSUE THREAD

**Issue by Majkl578** [Kdyby/Clock#7]
Because it's just not needed. DI extension should be in separate package (so Symfony Bundle could be as well).

**Comment by Majkl578** [comment]
@fprochazka: What do you think would be an optimal approach to resolve this?

**Comment by fprochazka** [comment]
People are expecting this package to be the integration. So it's no easy task so uncluther this.

**Comment by Majkl578** [comment]
I'd like to use this in Symfony application soon, thus I don't want any Nette\Application-related dependency in there. It should be probably split into two packages anyway, not sure how though.

**Comment by fprochazka** [comment]
@Majkl578 I agree. On the not knowing how (yet) too :)

**Comment by Majkl578** [comment]
Nette dependency is gone as of 087b34bb0, but DI extension is still here.

How about making new repos: ClockExtension for Nette integration and ClockBundle for Symfony integration? What do you think? @fprochazka @richard-ejem

**Comment by Majkl578** [comment]
bump

**Comment by mabar** [comment]
I would like this solution:
Clock in standalone package and package for each framework. Framework specific package should symlink clock. In this case user still install only one package and dependencies are correctly splitted.
It can be did with [submodules](https://git-scm.com/docs/git-submodule) [(example)](https://github.com/adeira/superproject)

**Comment by fprochazka** [comment]
I'm strongly against using submodules, when we have composer.

**Comment by richard-ejem** [comment]
I think we can agree to do it as @Majkl578 suggested - one "framework agnostic" package and one for each framework.

**Comment by fprochazka** [comment]
So, I'm thinking I'm gonna release versions for nette 2.3 and 2.4 and then deprecate the package in favour of [damejidlo/datetime-factory](https://github.com/damejidlo/datetime-factory)

**Comment by Majkl578** [comment]
Ok, unfortunately I'll have to maintain a fork/resurrection then, since I don't think damejidlo/datetime-factory is a sufficient replacement.

**Comment by enumag** [comment]
I agree with @Majkl578.

**Comment by fprochazka** [comment]
It's open to discussion :)

**Comment by fprochazka** [comment]
My thought was that it might be a sufficient replacement. But if you disagree, I'd be happy to not deprecate this :)

**Comment by fprochazka** [comment]
Okey, so If I were to not deprecate this, how about this plan:

* extract `kdyby/datetime-provider` into namespace `Kdyby\DatetimeProvider` from this package (the classes without DI extension)
* rename `kdyby/clock` to something like `kdyby/nette-datetime-provider` (or `kdyby/datetime-provider-nette` ? )
    * github redirects correctly, this should not break any existing application
    * create new package `kdyby/nette-datetime-provider` on packagist and deprecate `kdyby/clock` package in favour of this package - https://github.com/composer/packagist/issues/47#issuecomment-271962248
* create some `aliases.php` file with `class_alias()` calls to allow gradual refactoring of existing applications (that you'd have to require manually in your bootstrap file)

**Comment by enumag** [comment]
Sounds good. Just not sure about `Kdyby\DatetimeProvider` vs `Kdyby\DateTimeProvider` (for consistency with php classes)?

**Comment by Majkl578** [comment]
Hi, I've done a huge refactoring in the experimental branch, so if you could take a look and give some feedback, it'd be awesome!

**Comment by enumag** [comment]
I like it. Just a minor thing I'd turn around the PHP version check in ImmutableProviderTrait - PHP < 7.1.7 is the special case, clone is the prefered behavior. Some static analysis might complain about useless else in ConstantProviderFactory. In ImmutableProviderTrait you missed `{@inheritdoc}`. Otherwise good. 👍

**Comment by richard-ejem** [comment]
@Majkl578 what about creating a WIP merge request so we can discuss on the code directly?
@enumag 1) I think the 7.1.7 condition is correct, as clone was somehow broken before that version? 2) how is the `else` useless? the else can be reached and gives slightly different exception, so I do not see a problem.

**Comment by Majkl578** [comment]
@richard-ejem It's not meant to be ever merged into master, rather moved to new repository. Basically everything changed so it would be a messy diff anyway. But feel free to comment on single commits. 😎
