### ISSUE TITLE
Use DateTimeImmutable

### ISSUE THREAD

**Issue by Majkl578** [Kdyby/Clock#8]
Since it's mature enough, it'd be convinient to require PHP 5.5+ and start returning DateTimeImmutable only. This involves a BC break, but for a good reason, we still have only a 0.* version anyway.

**Comment by fprochazka** [comment]
Tagging a new major would be required, but imho that's not a big deal.

**Comment by Majkl578** [comment]
I think new major isn't needed in this case, as per semver definition:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by fprochazka** [comment]
Solved in master, gonna lat that lay there for a bit and then we can tag v1.0
